### ISSUE TITLE
Unable to find valid certification

### ISSUE THREAD

**Issue by damianpoole** [ctechols/makerMessage#1]
Using the google search I believe I need to add the ifttt ssl certificate into my keytool... ?

I believe I have done that, it shows using keytool -list however I still seem to get the same error... is there some setup missing from the installation instructions?

```
Caught: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at makerMessage.run(makerMessage:74)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    ... 1 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    ... 1 more
```

**Comment by ctechols** [comment]
Hi Damian,

I'm not sure why you're having this problem.  I didn't have to do anything
with the keystore to get it to work, so my suggestion will be grasping at
straws.

It might be that for some reason, your keystore doesn't have the root
certificate for the maker channel.  This particular root certificate is "Go
Daddy Root Certificate Authority - G2" with a SHA1 hash of
47:BE:AB:C9:22:EA:E8:0E:78:78:34:62:A7:9F:45:C2:54:FD:E6:8B. You can use
'keytool -list' on your jdk/jre's 'cacerts' file to verify that it contains
this certificate.

If I forcibly delete this root cert from my keystore, I can reproduce the
problem you describe.  However, I can't imagine why your system would have
this problem, that certificate should have shipped with your copy of java.

Note that IFTTT's maker channel has a different SSL certificate from the
rest of IFTTT.  The rest of IFTTT is signed with a root cert from
GlobalSign.

**Comment by damianpoole** [comment]
Typing keytool -list in terminal displays only the certificates I have added, seems I don't have any certificates shipped with the version of java I use. I've added the Go daddy certificate and it hasn't helped. Must be my java installation.

**Comment by ctechols** [comment]
You can explicitly name a keystore on the command line.  Java's global
keystore will usually either be $JAVA_HOME/jre/lib/security/cacerts or
$JAVA_HOME/lib/security/cacerts

For instance try:

keytool -list -keystore $JAVA_HOME/jre/lib/security/cacerts -v -storepass
changeit

The store's password usually really is 'changeit'.  The -v argument will
cause it to print all of the certificate attributes, including the common
name and all of the fingerprints.
